config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'resumes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
   validates :title, :attachment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)

    respond_to do |format|
      if @resume.save
        format.html { redirect_to @resume, notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.require(:resume).permit(:title, :category, :price, :year, :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jorah movie store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resumes/_form.html.erb
   <%= form_for @resume, html: { multipart: true } do |form| %>   

  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

app/views/resumes/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Inline|Bungee+Shade" rel="stylesheet">

<head>
<style>
* {
  box-sizing: border-box;
}
html, body, {
    position:fixed;
    top:0;
    bottom:0;
    left:0;
    right:0;
      object-fit: cover;
      background-color:#2f432f;

}
footer{
  background:black;
  position:relative;
  top:70px;
  height:50px;
  color:white;
}
.grid-container {
  display: grid;
  width:100%;
   grid-template-columns: repeat(auto-fill, minmax(190px, 5fr));

  padding:0px;
  grid-gap:20px;
  position:relative;
  top:60px;
  left:10px;
  

}
.grid-item {
  padding: 20px;
  height:250px;
  font-size: 30px;
  text-align: center;
  -webkit-box-shadow: -11px -8px 24px -11px rgba(15,10,15,1);
-moz-box-shadow: -11px -8px 24px -11px rgba(15,10,15,1);
box-shadow: -11px -8px 24px -11px rgba(15,10,15,1);
position:relative;
background:white;


}

   h1
   {
    color:red;
    opacity:0.7;
    text-decoration:none;
    padding:50px;
    font-size:25px;
    position:relative;
    top:-10px;
text-align:center;    

  }
  img:hover {
  opacity: 0.5;
  filter: alpha(opacity=50);
  }
  header{
    background:black;
    height:auto;
    width:100%;
    position:relative;
    top:-30px;
  }
  a
  {
    border:3px 2px solid gray;
    color:black;
  }
</style>
</head>
<body style="background-color:black;">

<header><h1>Jorah Movie Market</h1></header>

<%= link_to "Add movie", new_resume_path, style: "color:white; fontsize:18px;font-weight:bold;"  %>
<div class="grid-container">
<% @resumes.each do |resume| %>
  <div class="grid-item"><img src="<%= resume.attachment %>" style="width:100%;height:80%;padding:20px"/> <p class="card-text" style="color:green;">Title:<b><%= resume.title %></b><br>
              
<%= link_to 'Edit|', edit_resume_path(resume) ,style:"text-decoration:none;" %>
<%= link_to 'View|', resume ,style:"text-decoration:none;" %>
<%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } ,style:"text-decoration:none;" %>
</div>
  <% end %>  
</div>
<footer>
  <center><p>all right reserved by Himbaza@2019.</p></center>
</footer>
</body>
</html>

app/views/resumes/new.html.erb
<h1>New Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Back', resumes_path %>

app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resume.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @resume.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @resume.price %>
</p>

<p>
  <strong>Year:</strong>
  <%= @resume.year %>
</p>

<p>
  <strong>Attachment:</strong>
<img style="width:150px;height:150px;" src="<%= @resume.attachment %> "> </p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>